[package]
name = "movie-cm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "api/lib",
    "api/shuttle",
    "shared"
]
[[bin]]
name = "api"
path = "api/lib/src/lib.rs"

[dependencies]
